<a href="https://colab.research.google.com/github/vedantzope9/ML_mspa/blob/main/MSPA_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import tensorflow as tf
msg = tf.constant("Hello World!")
tf.print(msg)

Hello World!


In [3]:
x = tf.constant(1, tf.int32)
zeros = tf.zeros([2, 3], tf.int32)
ones = tf.ones([2, 3], tf.int32)
y = x *(zeros + ones + ones)

tf.print(y)

[[2 2 2]
 [2 2 2]]


In [14]:
W = tf.Variable(tf.random.normal([2,2], stddev=0.1),name = "W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")
print(W)
print(b)

<tf.Variable 'W:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.05709892,  0.01071787],
       [ 0.0572807 , -0.04348768]], dtype=float32)>
<tf.Variable 'b:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [17]:
import numpy as np
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
print (matrix1)
print (matrix2)

tf.Tensor(
[[2 2 2]
 [2 2 2]
 [2 2 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [18]:
matrix_product = tf.matmul(matrix1, matrix2)
print(matrix_product)

matrix_sum = tf.add(matrix1,matrix2)
print(matrix_sum)

tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [28]:
x = tf.Variable(2, name="x")
y = tf.Variable(4, name="y")
f = x*x + y*y + 2

print(f)

tf.Tensor(22, shape=(), dtype=int32)


In [31]:
tf.compat.v1.disable_eager_execution()
input = tf.compat.v1.placeholder(tf.float32, shape=(None, 2))
mul=input*2

with tf.compat.v1.Session() as sess:
  data = [[1, 2], [3, 4], [5, 6]]
  result = sess.run(mul, feed_dict={input: data})
  print("Result:\n",result)

Result:
 [[ 2.  4.]
 [ 6.  8.]
 [10. 12.]]


In [29]:
my_graph = tf.Graph()

with my_graph.as_default():
   a = tf.constant(2)
   b= tf.constant(3)
   add = a + b

with tf.compat.v1.Session (graph=my_graph) as sess:
  result = sess.run(add)

print("Result of a + b:", result)


Result of a + b: 5


In [30]:
t = tf.Variable(0)
def increment():
   t.assign(t + 1)

for _ in range(5):
  increment()
  var_value = t.numpy()
  print("After increment:", var_value)



After increment: 1
After increment: 2
After increment: 3
After increment: 4
After increment: 5
